### ISSUE TITLE
chore: Ed25519 is supported (at least) since 3.14.1.9

### ISSUE THREAD

**Issue by duesee** [rien/reStream#109]
Regarding ...

> Note: the reMarkable 2 doesn't support ed25519 keys. If it's your case, try generating an ecdsa or rsa key. Try out ssh root@10.11.99.1, it should not prompt for root@10.11.99.1's password.

I just tested (v3.14.1.9) and it works. I first had issues because ssh-copy-id seemed to copy the SSH key to `/etc/dropbear/authorized_keys`. This didn't work. I created the `/home/root/.ssh` directory and added `authorized_keys` file there.

This is a reminder for me. Maybe we should put this into the README as well?

By the way... Thanks for this awesome project! Works like a charm! :-)

**Comment by Eeems** [comment]
>  I first had issues because ssh-copy-id seemed to copy the SSH key to `/etc/dropbear/authorized_keys`

See the warning about OpenSSH versions before 9.4: https://remarkable.guide/guide/access/ssh.html#installing-a-ssh-key-on-your-device

**Comment by duesee** [comment]
Thanks!
