### ISSUE TITLE
Invalide buffer size

### ISSUE THREAD

**Issue by jwittke** [rien/reStream#15]
Hi,
when running  reStream I get an ffmpeg error:
```
[rawvideo @ 0x7f523c004400] Invalid buffer size, packet size 3215360 < expected frame_size 5271552
```
The screen shows but ffmpeg throws this error. 
I am using  ffplay version 4.1.4-1build2 and Remarkable 2.1.1.3

**Comment by rien** [comment]
Hi Jan

It's normal that when you stop `reStream` or close the window, it throws that error. That's because ffmpeg notices the connection is killed before a full frame is finished. If the screen of your reMarkable is shown like it should, you can just ignore this error.

**Comment by jwittke** [comment]
Nope, everything else is fine.
