### ISSUE TITLE
FrameBuffer as Video Device

### ISSUE THREAD

**Issue by ax3l** [rien/reStream#17]
Hi,

Thank you for sharing these scripts, that's awesome!

Do you know if I can use the streamed framebuffer as new "video" device on the host? I would like to select the reMarkable as a video source in WebRTC/Skype/Zoom/etc. calls and wonder what needs to be done for that.

Thanks a lot,
Axel

**Comment by beardhatcode** [comment]
I have a script that does exactly that. I'll make a PR for it.

**Comment by ax3l** [comment]
Oh wonderful, thank you @beardhatcode! :rocket: :sparkles:

**Comment by rien** [comment]
@ax3l could you try it out and report back if it works as expected?

**Comment by ax3l** [comment]
Thank you so much!

I had to upgrade my `v4l2-loopback` installation on Ubuntu 18.04 since prior to v0.12.0 [this bug](https://github.com/umlaeute/v4l2loopback/issues/172) prevents me from using it. Had to sign the self-build module [like this](https://github.com/umlaeute/v4l2loopback/issues/122#issuecomment-332393907) and now its working :)

One last practical aspect: should we add an option to mirror the video stream horizontally along the landscape toggle? An additional `hflip` filter did it for me :)
```diff
@@ -118,6 +119,7 @@ window_bytes="$((width * height * bytes_per_pixel))"
 
 # rotate 90 degrees if landscape=true
 $landscape && video_filters="$video_filters,transpose=1"
+$hflip && video_filters="$video_filters,hflip"
```

This is nice!!
