### ISSUE TITLE
Cannot use zstd even though already put into both computer and remarkable.

### ISSUE THREAD

**Issue by huijunchen9260** [rien/reStream#2]
The following is my error code. 

Somehow the shell cannot find zstd in the remarkable.

```
sh: /home/root/zstd: No such file or directory
```

I tried both dash and bash.

```
/usr/bin/zstd
ffplay version n4.2.2 Copyright (c) 2003-2019 the FFmpeg developers
  built with gcc 9.2.1 (Arch Linux 9.2.1+20200130-2) 20200130
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-nvdec --enable-nvenc --enable-omx --enable-shared --enable-version3
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
sh: /home/root/zstd: No such file or directory0KB sq=    0B f=0/0   
zstd: /*stdin*\: unexpected end of file 
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 1054310 kb/s
    Stream #0:0: Video: rawvideo (Y1[0][16] / 0x10003159), gray16le, 1408x1872, 1054310 kb/s, 25 tbr, 25 tbn, 25 tbc
```

**Comment by huijunchen9260** [comment]
If I log in the remarkable ssh and try to type it, it say no such file or directory, while zstd is actually there.

```sh
remarkable: ~/ /home/root/zstd                                                                                 
-sh: /home/root/zstd: No such file or directory
remarkable: ~/ ls zstd                                                                                         
zstd
```

**Comment by rien** [comment]
Strange. @huijunchen9260, what is your home directory on your remarkable? e.g. what does `pwd` produce?

**Comment by rien** [comment]
I have pushed a possible fix. Could you look if it fixes the problem?

**Comment by vdrummer** [comment]
I'm experiencing the same issue:

```
remarkable: ~/ pwd
/home/root
remarkable: ~/ ls zstd 
zstd
remarkable: ~/ ./zstd 
-sh: ./zstd: No such file or directory
remarkable: ~/ /home/root/zstd 
-sh: /home/root/zstd: No such file or directory
```

`sh` doesn't seem to find the binary if I try to execute it.

I tried the most recent version of the script (with `~/zstd`) but as you can see, the path doesn't seem to be the problem

**Comment by rien** [comment]
Ah, that is probably caused by entware. I gues I could try compiling a statically linked binary of `zstd`.

Thanks for troubleshooting!

**Comment by vdrummer** [comment]
I just had a look at the entware repo. It puts everything into `/opt` which is linked to `~/.entware` but `/opt` doesn't exist on the rM and is created during the installation of entware.
I think a statically linked binary would be the best solution for users without entware.

You're welcome. Awesome project, by the way!

**Comment by huijunchen9260** [comment]
After I tried the update version, it works!
Thank you for such an awesome project!

**Comment by rien** [comment]
I have switched to `lz4` in my latest commit (9f6ba5dd1d09a8f0f74a7dc810eb1a5c0549fc1a), which makes it a lot easier to install on the reMarkable (and as bonus: it's slightly faster!).

**Comment by vinipsmaker** [comment]
@rien, maybe you'll find this interesting: https://facebook.github.io/zstd/#small-data

With train data, zstd can beat lz4's speed. And it already has more throughput, so maybe better framerate. Although it's good to refrain ourselves from reimplementing a codec job using zstd and just stick to the basics.

Cool project, btw.
