### ISSUE TITLE
tag project with remarkable-tablet

### ISSUE THREAD

**Issue by Ameb** [rien/reStream#20]
In an effort to make projects for the reMarkable tablet easier to find on GitHub, a common topic named `remarkable-tablet` has been established (See [reHackable/awesome-reMarkable#1](https://github.com/reHackable/awesome-reMarkable/issues/1)).

It would be awesome if you could tag this project with the `remarkable-tablet` topic.
 
 There's more info on [Classifying your repository with topics](https://help.github.com/articles/classifying-your-repository-with-topics/) available in the GitHub help.
 
 A list of already tagged projects can be found here: [Projects in Topic remarkable-tablet](https://github.com/topics/remarkable-tablet).

**Comment by rien** [comment]
Done! Thank's for asking.
