### ISSUE TITLE
Possibility to zoom in in portrait mode

### ISSUE THREAD

**Issue by huijunchen9260** [rien/reStream#25]
Do you think is it possible to zoom in portrait mode?

Now I tend to use portrait mode, but somehow people will say that the screen is too small if I wrote smaller.

But I guess it is probably difficult in just POSIX sh...?

Screenshot that probably what why want (by [rmview](https://github.com/bordaigorl/rmview))
![image](https://user-images.githubusercontent.com/54217138/81031142-4a6b4900-8e59-11ea-8c92-84558df022ed.png)

Screenshot that people complains:
![image](https://user-images.githubusercontent.com/54217138/81031028-ddf04a00-8e58-11ea-9127-5d0cf2f58865.png)

**Comment by rien** [comment]
Hi there! That's definitely possible. You could zoom in by changing the `height` parameter to a smaller value (e.g. to 792 for an ideal 16/9 aspect ratio). You can find this parameter on line 74 in the script. However, this will throw away the bottom 2/3 of you screen, which is not ideal.

**Comment by huijunchen9260** [comment]
Yeah, the ideal way is to zoom in and zoom out instantaneously. Does it possible for `ffmpeg` to achieve such work?

**Comment by rien** [comment]
`ffplay`is able to cycle trough video filters with `w`, so I think it should be possible. But I don't know by hearth how you could achieve this. Ffmpeg's manpage or [documentation website](https://ffmpeg.org/ffmpeg-filters.html) would be good place to search for how to do this.

If you find a way, please report back so other people can also use your solution.

**Comment by rien** [comment]
@huijunchen9260 have you found a solution for your issue?

**Comment by huijunchen9260** [comment]
No. It turns out that I just use rmview.
