### ISSUE TITLE
no space to create dir

### ISSUE THREAD

**Issue by Jerithub** [rien/reStream#3]
I'm getting this error when trying to create the directory in order to install zstd
**mkdir: can't create directory '/opt/': No space left on device**

**Comment by huijunchen9260** [comment]
Connect to your remarkable using ssh, and run

`journalctl --vacuum-size=2M`

**Comment by rien** [comment]
I have switched to `lz4` for compression and the installation is now a lot easier. You shouldn't bump into this issue now, but let me know if you encounter other problems.
