### ISSUE TITLE
Liveview does not open on host (rM2 and git-bash on win10)

### ISSUE THREAD

**Issue by microbundle** [rien/reStream#32]
I just got my rM2 and I'd love to use it to screen-share and give talks online!
Unfortunately, so far I've been failing to get reStream to work with my win10 laptop. I get the following console output:

![console-output](https://user-images.githubusercontent.com/20144841/98470361-fe6cd880-21dc-11eb-888d-7e4028b66374.PNG)

This is the git-bash console on Windows 10. 
I've checked the following:

- I'm on the branch that is rM2 compatible
- As far as I can tell the shh is working fine
- lz4 is installed on both the host and the reMarkable
- ffplay seems to be working fine. ( `$ffplay  example.mp4` from the same command line opens a window playing the mp4)

I'm sure this is just me missing something obvious, but maybe this is helpful for future reference.

**Comment by rien** [comment]
The rM2 is currently unsupported, but we're trying to fix it over at #28 and #31.

**Comment by microbundle** [comment]
Sorry for that. I got confused because the "feature/support-reMarkable-2" branch has a "rM2|supported" badge. I'll give it another try once that's merged to the master.
Thanks for the quick response!
