### ISSUE TITLE
Ideas on Mouse support

### ISSUE THREAD

**Issue by stheid** [rien/reStream#37]
I am wondering if there are any ideas to incorporate mouse support. i guess this is technically as complex as the whole framebuffer thing, but would be extremely cool. (all following device files are for the RM2)

## my idea
- leftclick on the stream window: emulates touch event (`/dev/input/event2`) on remarkable, allowing to navigate between documents
- ctrl+leftmouse ": emulate digitizer (`/dev/input/event1`)  to allow basic drawing.

My first experiements show, that one can simply write to the device files. More precisely i can record and replay an event:
```
cat /dev/input/event2 > out # stop with ctrl+c
cat out > /dev/input/event2
```
Since the reading and decoding has already been done by other projects [1,2] i think the technical side should be not that challenging.

I think it would be a valueable addition, however i am not sure how much effort it would be.

[1] https://gitlab.com/afandian/pipes-and-paper/-/blob/master/server.py#L40-70
[2] https://github.com/canselcik/libremarkable/wiki/Reading-from-Wacom-I2C-Digitizer

**Comment by rien** [comment]
This script works with a single "data stream" to pass the framebuffer data to `ffmplay`. Reading and writing the input events is not the difficult thing here, it's combining the two streams that is not trivial in the current reStream setup.

I don't really see a practical use case for sending inputs **to** the reMarkable. If you want to draw using your computer, why would you go trough the reMarkable? There are plenty of virtual whiteboards and PDF annotation tools which have more features than the reMarkable.

**Comment by stheid** [comment]
After further investigation i understood that the project here does not provide a UI, but the window is actually only an instance of ffplay. Hence i will open this ticket for the rmView project. I already have done preliminary experiments with rmView, so if the developers except my contribution the feature (at least the "touch" related feature will probably be available there in near future.

**Comment by stheid** [comment]
> This script works with a single "data stream" to pass the framebuffer data to `ffmplay`. Reading and writing the input events is not the difficult thing here, it's combining the two streams that is not trivial in the current reStream setup.
> 
> I don't really see a practical use case for sending inputs **to** the reMarkable. If you want to draw using your computer, why would you go trough the reMarkable? There are plenty of virtual whiteboards and PDF annotation tools which have more features than the reMarkable.

As said, my main usecase would be to navigate documents and make small highlighting when using the remarkable in a video converence or so. but it would anyway be not worth the efford in this project.
