### ISSUE TITLE
Wish to be able to have portrait view

### ISSUE THREAD

**Issue by huijunchen9260** [rien/reStream#4]
![image](https://user-images.githubusercontent.com/54217138/76650117-5234fe00-6538-11ea-9342-1e1a3253267e.png)

Does it possible to have portrait view for portrait document, and landscape view for landscape document?

**Comment by rien** [comment]
Yes, if you change the following line:
https://github.com/rien/reStream/blob/9f6ba5dd1d09a8f0f74a7dc810eb1a5c0549fc1a/reStream.sh#L5
to `landscape=false` you have portrait view.
