### ISSUE TITLE
The restream binary is not installed on your reMarkable.

### ISSUE THREAD

**Issue by TanguySimon** [rien/reStream#40]
Hi, i tried installing restream, managed to add lz4 and the ssh key is authorised on the remarkable, but when I launch the program, i get this :

xxxxxxxxxxxxxxxxxxxxxx:~/Documents/GitHub/reStream$ ./reStream.sh
[SSH] true
[SSH] cat /sys/devices/soc0/machine
[SSH] [ ! -f ~/restream ]
The restream binary is not installed on your reMarkable.
Please install it using the instruction in the README:
https://github.com/rien/reStream/#installation

what does this mean?
btw thank you very much for this open source script!

**Comment by Eeems** [comment]
Did you read the readme at that link?

> Copy the restream executable to the reMarkable and make it executable.
> 
> ```
>  # scp restream.arm.static root@10.11.99.1:/home/root/restream
>  # ssh root@10.11.99.1 'chmod +x /home/root/restream'

**Comment by rien** [comment]
Hi @TanguySimon, we recently switched from using `lz4` and a bunch of linux utils to one dedicated executable to run on the reMarkable, this is the `restream` executable which is mentioned in the installation instruction (as the comment above mentions).
