### ISSUE TITLE
unsecure-connection in README.md

### ISSUE THREAD

**Issue by f3fora** [rien/reStream#51]
The documentation of `unsecure-connection` flag in `README.md` is missing.

I think it is sufficient to add a point in the **Usage/Options** section, for example

> - `-u --unsecure-connection`: send framebuffer data over an unencrypted TCP-connection, resulting in more fps and less load on the reMarkable. See **Unsecure Connection** for installation instructions.

And a subsection **Unsecure Connection** in **Requirements**. I do not use `apt`, so I do not know for Ubuntu how is call the package name of `netcat`, which provides the command `nc` and which [implementation](https://wiki.archlinux.org/index.php/Network_tools#Netcat) do you want to use.

**Comment by rien** [comment]
You are absolutely right!

I'll welcome a PR for this, but can look at this later myself if nobody has made one yet.

**Comment by rien** [comment]
Closed by #52
