### ISSUE TITLE
remarkable 2 (at least with version 2.7.0.51) do have root passwords

### ISSUE THREAD

**Issue by markpbaggett** [rien/reStream#67]
I was trying to add my ssh key to my reMarkable 2 running 2.7.0.51 of the software. The README states:

```
Note: the reMarkable 2 doesn't support ed25519 keys, those users should generate and rsa key. Try out ssh root@10.11.99.1, it should not prompt for a password.
```

When I try to copy my key to my reMarkable, I get prompted for a password:

```
$ ssh-copy-id -i ~/.ssh/id_rsa.pub root@10.11.99.1 
/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/mark/.ssh/id_rsa.pub"
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
root@10.11.99.1's password: 
```

The root password can be found in recent versions of the software by going to:

Settings > Help > Copyrights and licenses > General Information

Beneathe the GPLv3 Compliance statement, there is a paragraph that states the password:

```
To do so, this device acts as an USB ethernet device, and you can connect using the SSH protocol using the username `root` and the password `YourUniquePassword`
```

I'm not sure if the root password is new, but I wanted to share this with anyone else encountering this problem.

**Comment by danshick** [comment]
Nope, they've always had root passwords. You shouldn't be prompted by restream because restream uses ssh configuration flags to avoid password authentication.

When installing your ssh keys, you'll have to use this password once. After that, the keys will suffice.

**Comment by markpbaggett** [comment]
Ah @danshick.  I misunderstood.  For some reason I interpreted that there shouldn't be a root password.  Closing.

**Comment by RealMrBread** [comment]
Nevertheless, it helped me founding the root password on my remarkable

> Note: the reMarkable 2 doesn't support ed25519 keys, those users should generate and rsa key. Try out ssh root@10.11.99.1, it should not prompt for a password.
