### ISSUE TITLE
liveview not showing up on local machine

### ISSUE THREAD

**Issue by Dmarc** [rien/reStream#7]
Hello,

I followed the procedure with no error message. Yet the live-view screen does not pop-up on the computer after running "./reStream.sh". Attached is a screenshot of the terminal. Any idea of what is the problem ? The remarkable os version is 2.1.1.3, and I'm using archlinux with gnome desktop.
Thanks.
![Capture d’écran de 2020-03-30 18-52-04](https://user-images.githubusercontent.com/6707136/77953178-230ae480-72cd-11ea-855e-db3eaa186340.png)

**Comment by rien** [comment]
Can you try to set up an SSH key to authenticate with your reMarkable? [You can follow this guide](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) and add the key to your reMarkable with `ssh-copy-id root@10.11.99.1`.

**Comment by Dmarc** [comment]
Great, it works !! I was missing the last step: `ssh-copy-id root@10.11.99.1`
Maybe you should add this point in the installation guide.
Thanks for the great work !
