### ISSUE TITLE
Donation link?

### ISSUE THREAD

**Issue by StachuDotNet** [rien/reStream#72]
I use this thing for hours every day. How can I thank you?

(I realize it's a small script at the end of the day, but the simplicity and stability of this little script has been a blessing.)

**Comment by rien** [comment]
Hi @StachuDotNet, I'm glad to hear this project is helping you. Your post here is already enough to say thanks :hugs:. 

You're not the first one asking to give a donation, so I have updated the README. I am in no need for a financial compensation thanks to the education and the chances I received. So if you would like to donate, please do so to a charity that has the possibility to give someone else those chances as well, like [GirlsWhoCode](https://girlswhocode.com/), [CoderDojo](https://coderdojo.com/), etc.
