### ISSUE TITLE
grabbing a single frame as CLI argument or image fileformat

### ISSUE THREAD

**Issue by Utopiah** [rien/reStream#75]
I often need to grab a single image in order to add to my online notebooks or share a drawing to friends and colleagues. What I end up doing is the following

```
rm rm2.jpg; reStream.sh -s remarkable2 -p -o rm2.jpg & sleep 10 && kill $!; gwenview rm2.jpg
```

It works reliably well but it's not straightforward. 

PS: just discovered https://github.com/cloudsftp/reSnap , not sure if that's better to have 2 separate utilities when arguably most of the work is already done here.

**Comment by rien** [comment]
I think having a dedicated tool for taking screenshots is better than including it in reStream.
