### ISSUE TITLE
OpenSSH 8.8 ssh-rsa problem

### ISSUE THREAD

**Issue by gitlyap** [rien/reStream#77]
There is a problem when trying to log in via OpenSSH 8.8. To solve this, the following options must be added to the script
- ```PubkeyAcceptedKeyTypes +ssh-rsa```
- ```HostKeyAlgorithms +ssh-rsa```

In line 93 the ssh call must be adapted as follows: ```ssh -o ConnectTimeout=1 -o PasswordAuthentication=no -o PubkeyAcceptedKeyTypes=+ssh-rsa -o HostKeyAlgorithms=+ssh-rsa "root@$remarkable" "$@"```

**Comment by rien** [comment]
Thank you for notifying this. I'll try to create a PR and release a new version soon.
