### ISSUE TITLE
Error when running reStream.sh

### ISSUE THREAD

**Issue by oren** [rien/reStream#78]
My tablet is 2.10.2.356-patch_27.2.01-0-gbbf4bcd. my laptop is ubuntu.
I installed the reStream on my laptop and on my tablet. I am running it from my laptop and see this message:
```
Error: Could not find pid of xochitl, is xochitl running?
```

**Comment by oren** [comment]
(just trying to provide more information)
no the rm, I believe the executable is in the right place and looks ok:

```
ls -l /home/root/restream
-rwxr-xr-x
```

**Comment by rien** [comment]
Hi @oren

Can you post the full error log? Normally the error message you receive should be surrounded by other output from the script.

If that is not the case, you may be running the executable directly. You need to run the `reStream.sh` script on your laptop in order for this to work.

If you _are_ running the script in your laptop, then the executable is working correctly but you are not running xochitl, this is needed on the rM2 unless you have installed [rm2fb](https://github.com/ddvk/remarkable2-framebuffer), but in that case it should detect that the framebuffer is located at `/dev/shm/swtfb.01`.

**Comment by oren** [comment]
i am not sure what changed but it's working now. thank you!
