### ISSUE TITLE
Optional Parameters

### ISSUE THREAD

**Issue by AaronDavidSchneider** [rien/reStream#8]
I really love your component! I experienced sub second latencies even using WiFi.
I think it would be nice if one could use WiFi as an automatic fallback (if the ip is provided in the script) if usb is not available.
And also a command line option to specify if you want to use horizontal or vertical mode. 
In my opinion these two things would be quite handy. What do you think?

I could implement this and open a PR, if you want me to.

Thanks again for this awesome method!

**Comment by rien** [comment]
Hi Aaron, nice to hear this also works over WiFi. I wasn't expecting
that to work.

Command line options is something I was thinking about integrating, so
you're very welcome to implement it! There is already a config parameter
(landscape=true) which changes the orientation.

I'm looking forward to your PR.
