### ISSUE TITLE
1.2.0 not fully released

### ISSUE THREAD

**Issue by TheAlgorythm** [rien/reStream#81]
I've tried to install the new package manually, as it is not on toltec, on the reMarkable but the download url `https://github.com/rien/reStream/releases/latest/download/restream.arm.static` in the README resolves to a 404 as there is not such a build artifact.
`https://github.com/rien/reStream/releases/latest/download/reStream.sh` also doesn't work.
PS Imho it isn't a good idea to have a build artifact like `restream.arm.static` in a git repository but i'm not a git expert.

**Comment by Myridium** [comment]
Usually git 'large file storage' or `git-lfs` would be used for packaging binaries on the releases page of a project. It is a bit confusing that the releases page contains source, and the repository contains the binary.

**Comment by rien** [comment]
Apologies for the delay, I have added the binary and script to the 1.2.0 release.
