### ISSUE TITLE
Streamed video is too dark, recordings are corrupted

### ISSUE THREAD

**Issue by Jacajack** [rien/reStream#91]
I'm having issues with reStream v1.2.0. The streamed video (`restream -s remarkable -p`) appears really dark:

<img src=https://user-images.githubusercontent.com/6173262/228895671-3a775042-e891-4b3d-ae41-f86fada42103.png width=300px>

When I use `restream -s remarkable -p -o test.mp4`, I get a broken MP4 file which looks like this:

<img src=https://user-images.githubusercontent.com/6173262/228895612-7ada4e26-64f1-4764-aa8b-81aeb77301ca.png width=300px>

Remarkable firmware version: 3.3.2.1655
Ffmpeg version: 5.1.2

**Comment by tbellembois** [comment]
I have the same issue.
Remarkable firmware version: 3.3.2.1655
Ffmpeg version: 4.4.2

Tried on  WIFI and USB.

**Comment by vunhatchuong** [comment]
Heard it's a rm2fb issue, we just need to wait till rm2fb support the version.

**Comment by Jayy001** [comment]
3.2.3.1595 - Running a webserver+ffmpeg+websocket+restream on the ReMarkable device it self. 
![hello](https://user-images.githubusercontent.com/56607897/232044136-b7b42e19-9bcc-449f-93d4-365cd30f3727.gif)

https://github.com/ddvk/remarkable2-framebuffer/pull/120 Offsets here

**Comment by plamenivanov257** [comment]
Can confirm that I am experiencing the same issue (dark screen). Reading the code in reStream.sh, it seems to be because it defaults to grayscale since it cannot find /dev/shm/swtfb.01 on the reMarkable device. Is this some shared-memory frame buffer that is no longer available on the latest firmware?

Not sure why the grayscale is so dark, **but fortunately there is a workaround** --- one can add a gamma filter to ffmpeg. To do this, simply modify line 15 of reStream.sh to read 

`video_filters="eq=gamma=10"`

This cranks up the gamma to the max allowed value in ffmpeg. The result is not perfect but still very usable for many things.

**Comment by Eeems** [comment]
> Can confirm that I am experiencing the same issue (dark screen). Reading the code in reStream.sh, it seems to be because it defaults to grayscale since it cannot find /dev/shm/swtfb.01 on the reMarkable device. Is this some shared-memory frame buffer that is no longer available on the latest firmware?

That would be provided by rm2fb. See the last couple comments before yours.

**Comment by plamenivanov257** [comment]
Is it? I never installed rm2fb and I cannot find any references to rm2fb in either the host or device code for reStream...

**Comment by Eeems** [comment]
> Is it? I never installed rm2fb and I cannot find any references to rm2fb in either the host or device code for reStream...
> 
> Maybe I have always used grayscale without knowing and something somewhere somehow broke that?

`/dev/shm/swtfb.01` is a reference to rm2fb. It's shared memory provided by rm2fb. PR #41 added support for rm2fb. You can find lots of discussion on supporting the rM2 on #28

**Comment by plamenivanov257** [comment]
Interesting... Apologies, I am new to this stuff. Thanks for the info!

So, just to be clear, does reStream somehow install rm2fb by itself? If not, then I guess I have always ran in grayscale mode and the darkness bug is not related to rm2fb...

**Comment by plamenivanov257** [comment]
> Yes, you would have always been running in greyscale mode.

This makes sense, thank you! I guess the question then is why the grayscale version is now broken since it was fine before the last OS update.

**Comment by Eeems** [comment]
My guess is that the framebuffer pixel format may have changed again.

**Comment by StachuDotNet** [comment]
> Not sure why the grayscale is so dark, **but fortunately there is a workaround** --- one can add a gamma filter to ffmpeg. To do this, simply modify line 15 of reStream.sh to read
> 
> `video_filters="eq=gamma=10"`
> 
> This cranks up the gamma to the max allowed value in ffmpeg. The result is not perfect but still very usable for many things.

This is really useful, thanks. If you end up finding a more effective set of video filters, please follow up :)
I've tried playing with ffmpeg settings and I feel like there's got to be a simple set of filters that would make the screen clear again in the interim, but haven't figured it out :)

**Comment by D1mme** [comment]
> > Not sure why the grayscale is so dark, **but fortunately there is a workaround** --- one can add a gamma filter to ffmpeg. To do this, simply modify line 15 of reStream.sh to read
> > `video_filters="eq=gamma=10"`
> > This cranks up the gamma to the max allowed value in ffmpeg. The result is not perfect but still very usable for many things.
> 
> This is really useful, thanks. If you end up finding a more effective set of video filters, please follow up :) I've tried playing with ffmpeg settings and I feel like there's got to be a simple set of filters that would make the screen clear again in the interim, but haven't figured it out :)

Hi. I've found a (near) perfect workaround using:
`video_filters="curves=all='0/0 0.07/1 1/1'"`

Hope this helps.

**Comment by rien** [comment]
This should be fixed in the latest release by #100. Let me know if you encounter any additional issues.
